//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DomainResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gym.Domain.Properties.DomainResources", typeof(DomainResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty..
        /// </summary>
        public static string Global_ValueCannotBeEmpty {
            get {
                return ResourceManager.GetString("Global_ValueCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile must be valid..
        /// </summary>
        public static string Gym_Mobile_MustBeValid {
            get {
                return ResourceManager.GetString("Gym_Mobile_MustBeElevenNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile must be start with 09..
        /// </summary>
        public static string Gym_Mobile_MustBeStartWith09 {
            get {
                return ResourceManager.GetString("Gym_Mobile_MustBeStartWith09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot contain invalid characters..
        /// </summary>
        public static string Name_CannotContainInvalidCharacters {
            get {
                return ResourceManager.GetString("Name_CannotContainInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot start with number..
        /// </summary>
        public static string Name_CannotStartWithNumber {
            get {
                return ResourceManager.GetString("Name_CannotStartWithNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be have at least bold character..
        /// </summary>
        public static string User_Password_MustBeHaveAtLeastOneBoldCharacter {
            get {
                return ResourceManager.GetString("User_Password_MustBeHaveAtLeastOneBoldCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be have at least number..
        /// </summary>
        public static string User_Password_MustBeHaveAtLeastOneNumber {
            get {
                return ResourceManager.GetString("User_Password_MustBeHaveAtLeastOneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be have at least symbol..
        /// </summary>
        public static string User_Password_MustBeHaveAtLeastOneSymbol {
            get {
                return ResourceManager.GetString("User_Password_MustBeHaveAtLeastOneSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot contain invalid characters..
        /// </summary>
        public static string User_Username_CannotContainInvalidCharacters {
            get {
                return ResourceManager.GetString("User_Username_CannotContainInvalidCharacters", resourceCulture);
            }
        }
    }
}
